### ISSUE TITLE
Firebase queue for Firestore?

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/firebase-queue#7]
@LoveMHz:
> @EECOLOR What at do you purpose is the best solution? A new project or try to expand firebase-queue to support Firestore?
>
> I've managed to hack together Firestore support, but not actually sure it fits in with the current project.

**Comment by EECOLOR** [comment]
Great question!

I do not think this library can support Firestore. There are a few reasons:
- The Firestore API is very different from the Realtime database API
- There is (at the moment of writing) no way to locally test Firestore

Another thing that might be problematic is that we are not using Firestore in any of our projects. This would have a negative effect if we had Firestore support in this project:
- We would need to completely rely on outside contributors to maintain that part of the library
- If someone asked a question we might not be able to answer it

So I think the best thing would be a separate project with maintainers that know how Firestore works. I would suggest to use the same surface API and behavior (as far as possible) as this library. This would benefit end-users (developers) and allows them to switch their application to another store. If it helps feel free to fork this library and convert it into a Firestore version!

**Comment by EECOLOR** [comment]
Ohw, I forgot to add: please let me know if you disagree, I try to be open for discussion.

**Comment by ElectroBuddha** [comment]
It is also possible to use both Realtime DB and Firestore DB in the same project. So one could, for example, separate logic needed for queuing to use RealtimeDB and keep the rest of your application on the Firestore DB.

**Comment by EECOLOR** [comment]
I'm closing this issue. If any feels it needs to be reopened, please feel free and don't forget to add a motivation and counter arguments.
