### ISSUE TITLE
_id field not  available on task

### ISSUE THREAD

**Issue by henry74** [kaliberjs/firebase-queue#8]
The original firebase-queue provided a handle to the unique task id through task._id.  For your implementation, this returns 'undefined'.  Is there another way to get to the original task id?

**Comment by EECOLOR** [comment]
Yes there is. The second argument of the `processTask` function contains a `snapshot` property which will give you access to the `key`. More information here: https://github.com/kaliberjs/firebase-queue/blob/master/docs/guide.md#the-processtask-function

**Comment by EECOLOR** [comment]
The lack of the `sanitize` option is also mentioned here: https://github.com/kaliberjs/firebase-queue#no-more-sanitize
